disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - line_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
opt_in_rules: # some rules are only opt-in
  - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
force_cast: warning # implicitly
