 platform :ios, '16.0'

target 'TradeMySurf' do
  # project 'TradeMySurf/SurfCurve.xcodeproj'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  inhibit_all_warnings!

  use_frameworks!

  pod 'SwiftyPickerPopover'
  pod 'lottie-ios'
  pod 'Presentr'
  
  target 'TradeMySurfTests' do
    inherit! :search_paths
    # Pods for testing
   end
end
